### PR TITLE
Jeromegn dbversions count

### PR DESCRIPTION
**Pull request by tantaman**
clean up history and remove merge commits from https://github.com/vlcn-io/cr-sqlite/pull/310

### CODE REVIEW

**Comment by tantaman** [comment]
This is a pretty big regression in terms of regular insert and update performance.

E.g.,

```sql
INSERT INTO base_table VALUES (...)
UPDATE base_table SET .... WHERE ...
```

# Update Perf

## Before

Screenshot 2023-08-06 at 6 50 28 AM

## After
Screenshot 2023-08-06 at 6 49 46 AM


# Insert Perf

## Before

Screenshot 2023-08-06 at 6 50 54 AM

## After

Screenshot 2023-08-06 at 6 51 16 AM

@jeromegn - what do you think of making this an optional bit of metadata to track?

**Comment by tantaman** [comment]
Optional as a compile time option

**Comment by jeromegn** [comment]
> Optional as a compile time option

That would work for us as a temporary workaround for the performance regression, but I'd say we'd eventually want to be able to profit from the full performance of cr-sqlite.

Any pointers on how to do that? I guess I can add a compile-time feature.

**Comment by jeromegn** [comment]
Looking at this some more: does the benchmark use a WAL journal? I didn't eyeball such a big regression in my manual testing, but maybe cr-sqlite got better before and I didn't get a feel for the new perf before my change.

**Pull request closed without merging**
