### PR TITLE
lookaside for primary keys. Replaces #344

### PR DESCRIPTION
**Pull request by tantaman**
Replaces #344 

TODO:
- [x] Update trigger functions to lookup from lookaside first
- [x] Update vtab to join in lookaside on read
- [x] Update vtab to merge using lookaside
- ~~Move sentinel record to lookaside?~~ : not doing this since it makes pulling changes quite difficult.
- [x] Backfill logic & automigrate logic
- [ ] rowid fixup?
   - key * 100 + col_offset
   - search thru everywhere in rust code for `rowid` and swap to new algorithm

Test key creation:
- Stable rowid in all circumstances (re-insert, update, insert, delete, insert or ignore/replace/onconflict)
- Always exists after each op
- Created for mergers of new rows
- Not created for merges of existing rows
- Not created or deleted for merges of existing rows that are deleteed
- Created for mergers of deletions for unseen rows

### CODE REVIEW

**Comment by tantaman** [comment]
There's a regression to insert performance (https://github.com/vlcn-io/cr-sqlite/blob/c26d2f8a088fadc1cdca7b592f8cb73101e8feff/py/perf/perf.ipynb). Apparently writing an extra table is a heavy (~20%) hit.

This is probably worth it given the storage savings. Users will most likely use `uuids` for primary keys in CRRs so we can save ~12-14 bytes per column with this. For users with compound primary keys, the savings are greater.

**Comment by tantaman** [comment]
@jeromegn - everything looks good if you want to give it a spin.

I'm going to write a few more tests still before merging.

**Comment by jeromegn** [comment]
Nice!

What about the remaining tasks? I fear they'd require a new migration.

**Comment by tantaman** [comment]
The rowid change will not since virtual tables don't actually save a rowid.

I don't think I'm going to move the sentinel information out of the clock tables since it will require ordering another set of tables when reading changes out.

**Comment by gorbak25** [comment]
Hi! I'm currently working on a [major metadata redesign](https://github.com/superfly/cr-sqlite/blob/fa34016064189463fe6629dddf5d17938ae62178/README.md#v2-metadata-format) for crsqlite to make it more efficient. Hashed keys are part of the new design. It will soon become part of [corrosion](https://github.com/superfly/corrosion) and get rolled out across the fly.io fleet!

**Pull request merged**
